name: Approve Cleanup

on:
  workflow_dispatch: # Manually triggered via Slack approval

jobs:
  approve-cleanup:
    runs-on: ubuntu-latest

    env: # Declare environment variables for all steps in this job
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::992382613070:role/github-actions-cleanup-role
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Perform Cleanup
        run: |
          python cloud_cleanup.py --dry-run=False # Perform actual cleanup

      - name: Generate Cleanup Report
        run: |
          zip cleanup-report.zip cloud_cleanup_report_*.csv

      - name: Upload Cleanup Report
        uses: actions/upload-artifact@v3
        with:
          name: approved-cleanup-report
          path: cleanup-report.zip

      - name: Notify via Slack with cURL
        run: |
          curl -X POST -H "Authorization: Bearer ${{ env.SLACK_BOT_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "channel": "${{ env.CHANNEL_ID }}",
            "text": "Cleanup completed and approved. The report has been uploaded as an artifact in GitHub Actions.",
            "attachments": [
              {
                "text": "You can download the cleanup report from the GitHub Actions artifacts.",
                "color": "#36a64f"
              }
            ]
          }' https://slack.com/api/chat.postMessage